# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dTalk

  target 'dTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dTalkUITests' do
    # Pods for testing
  end

end
